services:
  postgres:
    container_name: postgres
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: compose
    ports:
      - '5432'
    networks:
      - red_cross_network
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data

volumes:
  postgres:

networks:
  red_cross_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16
